CREATE TABLE PRODUCT(
    id BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    order_number VARCHAR(200) NOT NULL,
    product_id VARCHAR(200) NOT NULL,
    product_type VARCHAR(200) NOT NULL,
    sku VARCHAR(200) NOT NULL,
    price VARCHAR(200) NOT NULL
);
